apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-yjtm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-yjtm
    app.kubernetes.io/part-of: test-app-cpkz
  name: maven-hello-world-yjtm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-yjtm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-yjtm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-iwxv-tenant/test-app-cpkz/maven-hello-world-yjtm@sha256:87a9ad555f8b38215c1e912980c033b23781f92112d2bce299dd47f5ef4bd7ad
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
